version: "3.9"

services:
  api:
    build: .
    container_name: california-api
    ports:
      - "8000:8000"
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app

  streamlit:
    build: .
    container_name: california-streamlit
    ports:
      - "8501:8501"
    command: streamlit run app/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - .:/app
    depends_on:
      - api
