name: CI - Tests & Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 1 : Vérification du formatage avec black
      - name: Run black (check mode)
        run: |
          black --check .

      # Étape 2 : Vérification qualité du code avec flake8
      - name: Run flake8
        run: |
          flake8 .

      # Étape 3 : Lancer les tests pytest
      # commentaire pour test de lancement de ci.yml
      - name: Run pytest
        run: |
          pytest
